### ISSUE TITLE
Question about THUMOS'14 feature extractor model

### ISSUE THREAD

**Issue by yklilfft** [frostinassiky/gtad#12]
Appreciate for your code release! Awesome work!

I noticed that u have released THUMOS features, would u please share feature extractor model or code .GitHub address is also OK!
thanks a lot!

**Comment by coolbay** [comment]
Hi, @yklilfft ! We use the TSN model pre-tained on Kinetics to extract the features. Please refer to the [TSN repository](https://github.com/yjxiong/temporal-segment-networks) for the extractor code. There are pre-trained pytorch models in [this repository](https://github.com/coolbay/caffe2pytorch-tsn), which you can directly use to generate your features.
