### ISSUE TITLE
Error during running gtad_train.py

### ISSUE THREAD

**Issue by ingur** [frostinassiky/gtad#15]
Hi, while trying to train G-TAD I always end up with the following error:

```
???
sys:1: RuntimeWarning: Traceback of forward call that caused the error:
  File "gtad_train.py", line 153, in <module>
    train(train_loader, model, optimizer, epoch, mask)
  File "gtad_train.py", line 54, in train
    subgraph_loss = subgraph_loss_func(confidence_map, gt_iou_map, bm_mask)
  File "/home/jlam/dev/gtad/gtad_lib/loss_function.py", line 28, in subgraph_loss_func
    wce_loss = pem_reg_loss_func(pred_bm_wcs, gt_iou_map, bm_mask)
  File "/home/jlam/dev/gtad/gtad_lib/loss_function.py", line 127, in pem_reg_loss_func
    loss = F.mse_loss(pred_score * weights, gt_iou_map * weights)
  File "/home/jlam/anaconda3/envs/gtad/lib/python3.7/site-packages/torch/nn/functional.py", line 2257, in mse_loss
    ret = torch._C._nn.mse_loss(expanded_input, expanded_target, _Reduction.get_enum(reduction))

Traceback (most recent call last):
  File "gtad_train.py", line 153, in <module>
    train(train_loader, model, optimizer, epoch, mask)
  File "gtad_train.py", line 61, in train
    loss.backward()
  File "/home/jlam/anaconda3/envs/gtad/lib/python3.7/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jlam/anaconda3/envs/gtad/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function 'MseLossBackward' returned nan values in its 0th output.
```

I'm using a 2080ti GPU (driver ver 418.88) with CUDA release 10.0, V10.0.130. I reduced the `batch_size` to avoid memory issues and set the `n_gpu` parameter to 1. The error always happens at the same point a few minutes into training.

Please let me know if there's something I'm doing wrong,
Ingur

**Comment by frostinassiky** [comment]
Hi @ingurv , thanks for your interests in this work!

As @coolbay mentioned in #13 , If you use too small a batch size, it might happen that **no positive samples exist** in the batch. As a consequence, the memory error like this would occur.

You did not do anything wrong. I met this case before, please try to increase the batch size as the most straight forward solution. Besides, you can skip the training iteration when no positive samples exist.

**Comment by minghchen** [comment]
I encounter the same issue, and I solve it as the following.
I found we should add drop_last=True for train_loader, otherwise, the last training batch would be too small. 

`train_loader = torch.utils.data.DataLoader(VideoDataSet(opt, subset="train"),
                                               batch_size=opt["batch_size"], shuffle=True,
                                               num_workers=8, pin_memory=True, drop_last=True)`
