### ISSUE TITLE
how to get uNet_test.npy??

### ISSUE THREAD

**Issue by Aries5522** [frostinassiky/gtad#18]
thanks for sharing code!!
I have a questions in you rep.
Becaues I want to run on my own dataset,and in postprocess I met this problem??
Looking forword your reply,thanks

**Comment by frostinassiky** [comment]
Hi @Aries5522 . Thanks for your interest in G-TAD. 

`uNet_test.npy` contains the classification results for each video in the test set. You can use **any** video classification model to produce the prediction.

**Comment by frostinassiky** [comment]
Duplicate of #10

**Comment by Aries5522** [comment]
Thanks for your reply。I will to train my own classification model to classified the proposal.
