### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by dairui01** [frostinassiky/gtad#20]
Hello,

Thanks for releasing the code.
I faced this "Segmentation fault" problem when I run: Python align.py
btw, I did not face any problem while running: python setup.py install

Thanks

**Comment by dairui01** [comment]
I face this issue on both 4xRTX 2080 Ti and 4x1080Ti.

**Comment by frostinassiky** [comment]
Hi @dairui01 Thanks for your interest in G-TAD!

Given the limited information, I can hardly know what is going on. 

Could you provide the error log, such that we can have potential clues?

**Comment by dairui01** [comment]
Hi @frostinassiky Thanks for your reply!

I face this problem when I test the **Align1D2.2.0** layer. 
The error appears at **L76** in gtad/align.py: **output = layer(input, proposal)**

Actually, I did not change the code in gtad/align.py and the error log I got is just the 'Segmentation fault':

---------------------------------------
(gtad) [rdai@gpu10 gtad_lib]$ python align.py
- input shape is torch.Size([1, 2, 10])
- input mean is tensor(10.5000, device='cuda:0')
- rois shape is torch.Size([1, 2])
- rois is on 0
Segmentation fault
---------------------------------------

**I successfully create the conda environment and installed the Align1D2.2.0.**  
**I tested on 4xtitan X, 4x1080ti and 4x2080ti, always face the same error.**

**For more information, here is the log when I installed the Align1D2.2.0:**

running install
running bdist_egg
running egg_info
writing Align1D.egg-info/PKG-INFO
writing dependency_links to Align1D.egg-info/dependency_links.txt
writing top-level names to Align1D.egg-info/top_level.txt
reading manifest file 'Align1D.egg-info/SOURCES.txt'
writing manifest file 'Align1D.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
/home/rdai/anaconda3/envs/gtad/lib/python3.7/site-packages/torch/utils/cpp_extension.py:197: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (g++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.7/Align1D.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for Align1D.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/Align1D.py to Align1D.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.Align1D.cpython-37: module references __file__
creating 'dist/Align1D-2.2.0-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Align1D-2.2.0-py3.7-linux-x86_64.egg
removing '/home/rdai/anaconda3/envs/gtad/lib/python3.7/site-packages/Align1D-2.2.0-py3.7-linux-x86_64.egg' (and everything under it)
creating /home/rdai/anaconda3/envs/gtad/lib/python3.7/site-packages/Align1D-2.2.0-py3.7-linux-x86_64.egg
Extracting Align1D-2.2.0-py3.7-linux-x86_64.egg to /home/rdai/anaconda3/envs/gtad/lib/python3.7/site-packages
Align1D 2.2.0 is already the active version in easy-install.pth

Installed /home/rdai/anaconda3/envs/gtad/lib/python3.7/site-packages/Align1D-2.2.0-py3.7-linux-x86_64.egg
Processing dependencies for Align1D==2.2.0
Finished processing dependencies for Align1D==2.2.0



**Here is my conda environment:**

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
align1d                   2.2.0                    pypi_0    pypi
blas                      1.0                         mkl    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1               py37_0
cffi                      1.13.2           py37h2e261b9_0
cudatoolkit               10.0.130                      0
cycler                    0.10.0                   py37_0
dbus                      1.13.12              h746ee38_0
expat                     2.2.6                he6710b0_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_1
glib                      2.63.1               h5a9c865_0
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
h5py                      2.9.0            py37h7918eee_0
hdf5                      1.10.4               hb1b8bf9_0
icu                       58.2                 h9c2bf20_1
intel-openmp              2019.4                      243
joblib                    0.14.1                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2
kiwisolver                1.1.0            py37he6710b0_0
ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libpng                    1.6.37               hbc83047_0
libprotobuf               3.11.4               h8b12597_0    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.1.0                h2733197_0
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.9                hea5a465_1
matplotlib                3.1.0            py37h5429711_0
mkl                       2019.4                      243
mkl-service               2.3.0            py37he904b0f_0
mkl_fft                   1.0.15           py37ha843d7b_0
mkl_random                1.1.0            py37hd6b4f25_0
ncurses                   6.1                  he6710b0_1
ninja                     1.9.0            py37hfd86e86_0
numpy                     1.18.1           py37h4f9e942_0
numpy-base                1.18.1           py37hde5b4d6_1
olefile                   0.46                     py37_0
openssl                   1.1.1f               h516909a_0    conda-forge
pandas                    0.25.0           py37he6710b0_0
pcre                      8.43                 he6710b0_0
pillow                    7.0.0            py37hb39fc2d_0
pip                       20.0.2                   py37_1    conda-forge
protobuf                  3.11.4           py37h3340039_1    conda-forge
pycparser                 2.19                     py37_0
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.9.2            py37h05f1152_2
python                    3.7.6                h0371630_2
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.3.1           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
pytz                      2019.3                     py_0    conda-forge
qt                        5.9.7                h5867ecd_1
readline                  7.0                  h7b6447c_5
scipy                     1.4.1                    pypi_0    pypi
setuptools                45.1.0                   py37_0    conda-forge
sip                       4.19.8           py37hf484d3e_0
six                       1.14.0                   py37_0    conda-forge
sqlite                    3.31.1               h7b6447c_0
tensorboardx              2.0                        py_0    conda-forge
tk                        8.6.8                hbc83047_0
torchvision               0.3.0           py37_cu10.0.130_1    pytorch
tornado                   6.0.3            py37h7b6447c_0
tqdm                      4.32.1                     py_0    conda-forge
wheel                     0.34.2                   py37_0    conda-forge
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0


Thanks again

**Comment by frostinassiky** [comment]
Hi @dairui01 Thanks for your quick response. 

As the warning message indicates, please upgrade your GCC compiler to a higher version such as GCC 4.9 and above.

Here is the compiling log from my side:
```
xum@kw60220:~/gtad/gtad_lib$ python setup.py install
running install
running bdist_egg
running egg_info
creating Align1D.egg-info
writing Align1D.egg-info/PKG-INFO
writing dependency_links to Align1D.egg-info/dependency_links.txt
writing top-level names to Align1D.egg-info/top_level.txt
writing manifest file 'Align1D.egg-info/SOURCES.txt'
reading manifest file 'Align1D.egg-info/SOURCES.txt'
writing manifest file 'Align1D.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
building 'Align1D' extension
creating build
creating build/temp.linux-x86_64-3.7
gcc -pthread -B /home/xum/miniconda3/envs/G-TAD/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include -I/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include/TH -I/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include/THC -I/home/xum/miniconda3/envs/G-TAD/include/python3.7m -c Align1D_cuda.cpp -o build/temp.linux-x86_64-3.7/Align1D_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=Align1D -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/usr/local/cuda/bin/nvcc -I/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include -I/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include/TH -I/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include/THC -I/home/xum/miniconda3/envs/G-TAD/include/python3.7m -c Align1D_cuda_kernal.cu -o build/temp.linux-x86_64-3.7/Align1D_cuda_kernal.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --compiler-options '-fPIC' --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=Align1D -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
Align1D_cuda_kernal.cu: In lambda function:
Align1D_cuda_kernal.cu:227:120: warning: ‘c10::ScalarType detail::scalar_type(const at::Type&)’ is deprecated [-Wdeprecated-declarations]
   AT_DISPATCH_FLOATING_TYPES(input.type(), "Align1D_forward", [&] {
                                                                                                                        ^
/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:46:1: note: declared here
 inline at::ScalarType scalar_type(const at::Type &t) {
 ^~~~~~~~~~~
Align1D_cuda_kernal.cu: In lambda function:
Align1D_cuda_kernal.cu:269:118: warning: ‘c10::ScalarType detail::scalar_type(const at::Type&)’ is deprecated [-Wdeprecated-declarations]
   AT_DISPATCH_FLOATING_TYPES(grad.type(), "ROIAlign_backward", [&] {
                                                                                                                      ^
/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/torch/include/ATen/Dispatch.h:46:1: note: declared here
 inline at::ScalarType scalar_type(const at::Type &t) {
 ^~~~~~~~~~~
creating build/lib.linux-x86_64-3.7
g++ -pthread -shared -B /home/xum/miniconda3/envs/G-TAD/compiler_compat -L/home/xum/miniconda3/envs/G-TAD/lib -Wl,-rpath=/home/xum/miniconda3/envs/G-TAD/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/Align1D_cuda.o build/temp.linux-x86_64-3.7/Align1D_cuda_kernal.o -o build/lib.linux-x86_64-3.7/Align1D.cpython-37m-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.7/Align1D.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for Align1D.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/Align1D.py to Align1D.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.Align1D.cpython-37: module references __file__
creating dist
creating 'dist/Align1D-2.2.0-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Align1D-2.2.0-py3.7-linux-x86_64.egg
removing '/home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/Align1D-2.2.0-py3.7-linux-x86_64.egg' (and everything under it)
creating /home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/Align1D-2.2.0-py3.7-linux-x86_64.egg
Extracting Align1D-2.2.0-py3.7-linux-x86_64.egg to /home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages
Align1D 2.2.0 is already the active version in easy-install.pth

Installed /home/xum/miniconda3/envs/G-TAD/lib/python3.7/site-packages/Align1D-2.2.0-py3.7-linux-x86_64.egg
Processing dependencies for Align1D==2.2.0
Finished processing dependencies for Align1D==2.2.0
```

**Comment by frostinassiky** [comment]
Then you will be able to get the output as follows:
```
xum@kw60220:~/gtad/gtad_lib$ python align.py 
output has shape torch.Size([2, 2, 10]), with mean 8.550000190734863
tensor([[[ 1.0000,  2.0000,  3.0000,  4.0000,  5.0000,  6.0000,  7.0000,
           8.0000,  9.0000, 10.0000],
         [11.0000, 12.0000, 13.0000, 14.0000, 15.0000, 16.0000, 17.0000,
          18.0000, 19.0000, 20.0000]],

        [[ 1.1500,  1.2500,  1.3500,  1.4500,  1.5500,  1.6500,  1.7500,
           1.8500,  1.9500,  2.0500],
         [11.1500, 11.2500, 11.3500, 11.4500, 11.5500, 11.6500, 11.7500,
          11.8500, 11.9500, 12.0500]]], device='cuda:0')
```

**Comment by dairui01** [comment]
Hi @frostinassiky  Thanks again,
As you suggested, I upgraded my GCC compiler from 4.8 to 5 and reinstalled everything.
This time, there is no Warning for GCC but still facing the Segmentation fault error.
```
(g_tad) [rdai@nefgpu10 gtad_lib]$ python setup.py install
running install
running bdist_egg
running egg_info
writing Align1D.egg-info/PKG-INFO
writing dependency_links to Align1D.egg-info/dependency_links.txt
writing top-level names to Align1D.egg-info/top_level.txt
reading manifest file 'Align1D.egg-info/SOURCES.txt'
writing manifest file 'Align1D.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.7/Align1D.cpython-37m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for Align1D.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/Align1D.py to Align1D.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying Align1D.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.Align1D.cpython-37: module references __file__
creating 'dist/Align1D-2.2.0-py3.7-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing Align1D-2.2.0-py3.7-linux-x86_64.egg
creating /home/rdai/anaconda3/envs/g_tad/lib/python3.7/site-packages/Align1D-2.2.0-py3.7-linux-x86_64.egg
Extracting Align1D-2.2.0-py3.7-linux-x86_64.egg to /home/rdai/anaconda3/envs/g_tad/lib/python3.7/site-packages
Adding Align1D 2.2.0 to easy-install.pth file
Installed /home/rdai/anaconda3/envs/g_tad/lib/python3.7/site-packages/Align1D-2.2.0-py3.7-linux-x86_64.egg
Processing dependencies for Align1D==2.2.0
Finished processing dependencies for Align1D==2.2.0
```

```
(g_tad) [rdai@nefgpu10 gtad_lib]$ python align.py 
- input shape is torch.Size([1, 2, 10])
- input mean is tensor(10.5000, device='cuda:0')
- rois shape is torch.Size([1, 2])
- rois is on 0
Segmentation fault
```

**Comment by dairui01** [comment]
Hi @frostinassiky,

I updated the GCC from 4.8 to 6.2 and reinstall the CUDA/10 and cudnn/7.4-cuda-10.0.
This helps me solve this issue.
```
(gtad) [rdai@nefgpu10 gtad_lib]$ python align.py
output has shape torch.Size([2, 2, 10]), with mean 8.550000190734863
tensor([[[ 1.0000,  2.0000,  3.0000,  4.0000,  5.0000,  6.0000,  7.0000,
           8.0000,  9.0000, 10.0000],
         [11.0000, 12.0000, 13.0000, 14.0000, 15.0000, 16.0000, 17.0000,
          18.0000, 19.0000, 20.0000]],
        [[ 1.1500,  1.2500,  1.3500,  1.4500,  1.5500,  1.6500,  1.7500,
           1.8500,  1.9500,  2.0500],
         [11.1500, 11.2500, 11.3500, 11.4500, 11.5500, 11.6500, 11.7500,
          11.8500, 11.9500, 12.0500]]], device='cuda:0')
```
