### ISSUE TITLE
About h5 feature

### ISSUE THREAD

**Issue by yklilfft** [frostinassiky/gtad#25]
Thanks to your awesome work!
I notice that u use h5 to save extracted feature, I meet some troubles during extracting TSN features into h5 format. Would u please share code for THUOMS14 TSN features extraction as reference?

**Comment by Shuhan136** [comment]
I had the same problem and wanted code to extract the features.

**Comment by coolbay** [comment]
We use the TSN model pre-tained on Kinetics to extract the features. Please refer to the [TSN repository](https://github.com/yjxiong/temporal-segment-networks) for the extractor code. There are pre-trained pytorch models in [this repository](https://github.com/coolbay/caffe2pytorch-tsn), which you can directly use to generate your features.

Please indicate what specific problems you encounter for us to better help you.
