### ISSUE TITLE
H5 feature

### ISSUE THREAD

**Issue by Shuhan136** [frostinassiky/gtad#26]
Is the optical flow used in our method x_flow and y_flow, or is it a series of three channel frames？

**Comment by Shuhan136** [comment]
I notice that the value of feature_h5s is [ (810, 1024),       for “video_validation_0000051”
                                                                 (810, 1024）]
feature_h5s = [
                    self.flow_val[video_name][::self.skip_videoframes,...],
                    self.rgb_val[video_name][::self.skip_videoframes,...]

What dose 810 stand for ,What does 1024 stand for?

**Comment by Shuhan136** [comment]
In other words, what algorithm do you use to convert image frames and optical stream frames into 1024-dimensional features.

**Comment by frostinassiky** [comment]
Hi @Shuhan136 thanks for creating the issue.

We used the pre-trained action recognition model to extract feature from optical flow.
The extracted feature is with shape [N,C], where N is the number of snippets, and C is the number for channels. N is different in different videos (810 for “video_validation_0000051”) but C is fixed to be 1024. 

As for the algorithm we used, please read our paper. we mentioned
> For THUMOS-14, the video features are extracted using TSN model [44] pre-trained on Kinetics [57]
