### ISSUE TITLE
Is there a plan to upload ActivityNet feature?

### ISSUE THREAD

**Issue by OreoChocolate** [frostinassiky/gtad#27]
I want to run the model on Activitynet dataset.  Activitynet feature is not uploaded now.
Is there a plan to upload ActivityNet feature?

**Comment by frostinassiky** [comment]
Hi @OreoChocolate . Thanks for your interests in the work. 

I will upload the feature later. Before that, you can use the public feature from the [website](http://activity-net.org/challenges/2020/tasks/anet_localization.html), or extract by TSM or SlowFast.

**Comment by frostinassiky** [comment]
https://drive.google.com/drive/u/0/folders/1ilLgmZYHG1rx0ADuzAkW8jeqdEDeZ19g
