### ISSUE TITLE
Could you release the code on ActivityNet1.3？

### ISSUE THREAD

**Issue by JJBOY** [frostinassiky/gtad#28]
Hi, I am trying to reproduce your results on ActivityNet with CUHK classification results, but I got a poor result:
mAP at tIoU 0.5 is 0.4780277673855929
mAP at tIoU 0.55 is 0.4441596910099787                                                                                  
mAP at tIoU 0.6 is 0.41678668232272886                                                                                  
mAP at tIoU 0.65 is 0.3871944441767503                                                                                  
mAP at tIoU 0.7 is 0.35771643179213497                                                                                  
mAP at tIoU 0.75 is 0.3200403786921512                                                                                  
mAP at tIoU 0.8 is 0.28215867885824975                                                                                  
mAP at tIoU 0.85 is 0.23450290087046632                                                                                 
mAP at tIoU 0.9 is 0.17189101319827774                                                                   
mAP at tIoU 0.95 is 0.07244703532756719
average mAP is 0.3179219714302505 

I am not sure where is the problem, the hyper-parameters, the classification results or other reason?
I just replace the dataloader and post-processing code with https://github.com/JJBOY/BMN-Boundary-Matching-Network, and other settings stay the same.
Is there any plan to release the code on ActivityNet for easy reproduction?

**Comment by frostinassiky** [comment]
Hi @JJBOY Thanks for your interest in G-TAD! 

The configuration and post-processing of G-TAD are different from BMN. I did an extensive hyper-parameter search to get good performance. 

I do have the plan to update the repo for ActivityNet (and probability HACS), maybe later this year.

**Comment by JJBOY** [comment]
Thanks for your reply very much!
I am now doing some work based on your G-TAD. I hope to quickly reproduce the results of your paper to find to insight.
I am wondering could you please give a simple description about the differences or just share the key code?  So that I can quickly reproduce the results by myself soon.

**Comment by frostinassiky** [comment]
Please see the `anet` branch for the released code.

**Comment by mugenggeng** [comment]
Hi. Did you get a copy

**Comment by mugenggeng** [comment]
Hello, did you  reproduce the results of this paper in ActivityNet ?
