### ISSUE TITLE
Feature extraction - h5 files

### ISSUE THREAD

**Issue by destousok** [frostinassiky/gtad#29]
Hello! First of all your work is great!!

I would like to ask you some things about feature extraction and especially for the preparation of videos.

Let's say that I would like to use i3d for the feature extraction and I have extracted the rgb and optical flows for each video. Afterwards, i want to pass some segments of frames into the i3d and extract a feature vector (1024) for each segment. First of all, what number of frames should be into this segment and also these segments are going to be overlapped right? any ideas of what stride (over the frames) should I have for the overlapping?
Maybe we want features per frame?

Probably the way of using  i3d is different from tsn but I would appreciate any help you can provide! Thank you!

**Comment by frostinassiky** [comment]
Hi @destousok 

Thanks for your interests in this work!

If you want to obtain (very) dense feature, for example, the number of features equal to the number of frames, you can set the stride to 1, which means the overlap is (N-1). N is the number of frames in the segment.

In G-TAD, the feature is densely sampled, but we skipped each 5 feature to make it sparse. stride=5 is also a proper setting.
