### ISSUE TITLE
About THUMOS14 feature

### ISSUE THREAD

**Issue by souler256** [frostinassiky/gtad#31]
For THUMOS-14, the video features are extracted using TSN model pre-trained on Kinetics.  Can provide THUMOS-14 features extracted by TSN model pre-trained on Anet1.3(Xiong et. al. submit to ActivityNet Challenge 2016) or provide the code which extract THUMOS-14 features.  Thanks a lot.

**Comment by frostinassiky** [comment]
Hi @souler256 . Thanks for asking.

I did not use the feature extracted by TSN model pre-trained on Anet1.3 in my paper. 
I also do not have the code to extract that feature.

**Comment by thematrixduo** [comment]
Could you share how where do you get the features from? Is it the low-level feature from Thumos14 website?
