### ISSUE TITLE
Question About Classification for ActivityNet.

### ISSUE THREAD

**Issue by DRJ2016** [frostinassiky/gtad#33]
Sorry to disturb you. Really excellent work!

May I ask how to get the classification results of action in each video for ActivityNet 1.3 ?

Thank you!

**Comment by frostinassiky** [comment]
Hi @DRJ2016 , thanks for your interest! The classification result is from a pre-trained video classification model, such as TSN, TSM. 

The training of video classification is not covered by G-TAD work, but you can still find the result that I used in the `anet` branch.

https://github.com/frostinassiky/gtad/blob/anet/data/cuhk_val_simp_share.json

**Comment by DRJ2016** [comment]
Thank you for your reply.
