### ISSUE TITLE
Share the feature extraction code

### ISSUE THREAD

**Issue by mrlihellohorld** [frostinassiky/gtad#34]
Thank you very much for open source such excellent code, but I have a lot of confusion when using TSN to extract features and save them as.h5 files,Could you open source the key code to extract features?

**Comment by coolbay** [comment]
Hi, @mrlihellohorld ! Thanks for you question. 

Please refer to [this issue](https://github.com/frostinassiky/gtad/issues/25#issuecomment-662339921) for the feature extraction. If you still have questions, please describe the specific problems you have.

**Comment by mrlihellohorld** [comment]
> Hi, @mrlihellohorld ! Thanks for you question.
> 
> Please refer to [this issue](https://github.com/frostinassiky/gtad/issues/25#issuecomment-662339921) for the feature extraction. If you still have questions, please describe the specific problems you have.

Hi, @coolbay ! Thanks for your reply.
I have a look at the shape of the h5 file. For each video, should the feature be extracted for each frame and then saved?

**Comment by mrlihellohorld** [comment]
> > Hi, @mrlihellohorld ! Thanks for you question.
> > Please refer to [this issue](https://github.com/frostinassiky/gtad/issues/25#issuecomment-662339921) for the feature extraction. If you still have questions, please describe the specific problems you have.
> 
> Hi, @coolbay ! Thanks for your reply.
> I have a look at the shape of the h5 file. For each video, should the feature be extracted for each frame and then saved?

for example, /video_validation_0000661 have the shape: (5048, 1024). I understand that 5048 is the number of frames, so each video is storing the characteristics of each frame, right? thanks a lot!!!!
