### ISSUE TITLE
About align1D

### ISSUE THREAD

**Issue by wjn922** [frostinassiky/gtad#35]
Hi, 
     I want to know what the ratio represents in Align1DLayer. Thank you.

**Comment by frostinassiky** [comment]
Hi @wjn922, we use different ratio represents in the Align1D layer. 

We use τ1 = 32, τ2 = 4 for ActivityNet-1.3 and τ1 = τ2 = 16 for THUMOS-14. Please check Section 4.2 of the paper for implementation details.

**Comment by wjn922** [comment]
Hi, sorry for that I may not clarify my question. 
When define the Align1DLayer, the feature_dim is the τ as you mentioned, but I want to know what the second parameter ratio represent. Thank you!

![image](https://user-images.githubusercontent.com/21001460/103626730-9554d780-4f77-11eb-87d4-4aee4409e204.png)

**Comment by frostinassiky** [comment]
This is the sample ratio that I mentioned in Table 4, the first column. 

This variable can be
- 0: sample all frame;
- 1: sample each output position

Please see code here. If the ratio is zero, we will dynamically adjust the bin grid base on the input action length (duration) and τ.
https://github.com/frostinassiky/gtad/blob/6deb5b1bc6883b48bd22e0cc593069643c953e3d/gtad_lib/Align1D_cuda_kernal.cu#L175

**Comment by wjn922** [comment]
Got it. Thanks for your reply!
