### ISSUE TITLE
How to use this in video?

### ISSUE THREAD

**Issue by Malithi-gif** [frostinassiky/gtad#38]

**Comment by Malithi-gif** [comment]
@frostinassiky Can you explain how to use this in the actual video?

**Comment by frostinassiky** [comment]
Hi @Malithi-gif , thanks for your question.

Given an action video, we need to first extract the feature of each frame/snippet, and feed the feature to G-TAD. The output of G-TAD will show the action localization and the confidence score.

**Comment by Malithi-gif** [comment]
@ frostinassiky, Thank for your reply. Have you already used TSN pretrained
features? As you said, When we apply this into custom video dataset we
should extract the features as same way you did?
Why you used test annotation with start time and end time?

**Comment by frostinassiky** [comment]
Yes, I already used TSN pretrained features. We don't have to extract the features the same way I did -- but we should train G-TAD again if the video encoder is replaced.

For the second question, could you please let me know which line of code you are asking for?

**Comment by Malithi-gif** [comment]
@frostinassiky, Thanks for your reply. I talk about dataset.py. I mean this.
![image](https://user-images.githubusercontent.com/54534252/103879696-35d50400-50fe-11eb-9ee0-b4afa5849dc0.png)

Another thing is, Is this work for a single video?

**Comment by frostinassiky** [comment]
1. Test annotation is used to know the video names in the test dataset. 
Start time and end time are only used in training annotation 
https://github.com/frostinassiky/gtad/blob/6deb5b1bc6883b48bd22e0cc593069643c953e3d/gtad_lib/dataset.py#L205-L207

2. Yes, it works for a single video.

**Comment by Malithi-gif** [comment]
@frostinassiky  thanks for your reply. Can you explain how to apply this method for a single video? Should I need to get RGB and flow features using TSN model?

**Comment by frostinassiky** [comment]
Yes, you need to prepare RGB and flow features from TSN model, concatenate them, and feed the feature into the G-TAD model.
