### ISSUE TITLE
Detailed results on HACS Segments

### ISSUE THREAD

**Issue by xlliu7** [frostinassiky/gtad#40]
Hi @frostinassiky 
It's encouraging that GTAD also achieves a strong performance of 27,481 in terms of avg mAP on HACS Segments. Could you also share the detailed mAP values of G-TAD, including mAPs at IoU thresholds 0.5/0.75/0.95?

**Comment by xlliu7** [comment]
Hi all,
I've reproduced the results of G-TAD on HACS. The mAPs at IoU=0.5/0.75/0.95 are 41.08/27.59/8.34. The average mAP is 27.48.

**Comment by frostinassiky** [comment]
Thank you! @xlliu7 I will also upload the checkpoints once they are ready :P

**Comment by takfate** [comment]
> Hi all,
> I've reproduced the results of G-TAD on HACS. The mAPs at IoU=0.5/0.75/0.95 are 41.08/27.59/8.34. The average mAP is 27.48.

I'm sorry to ask, how did you reproduce it? I directly use the official i3d 
 features, read the .npy files, and interpolate to train. it seems that there is only 25 mAP.

**Comment by Mchhhhh** [comment]
> > Hi all,
> > I've reproduced the results of G-TAD on HACS. The mAPs at IoU=0.5/0.75/0.95 are 41.08/27.59/8.34. The average mAP is 27.48.
> 
> I'm sorry to ask, how did you reproduce it? I directly use the official i3d features, read the .npy files, and interpolate to train. it seems that there is only 25 mAP.

me too
Average-mAP: 0.2549818381400229
Detection: average-mAP 25.498 mAP@0.50 38.720 mAP@0.55 36.243 mAP@0.60 33.665 mAP@0.65 31.010 mAP@0.70 28.405 mAP@0.75 25.505 mAP@0.80 22.236 mAP@0.85 18.371 mAP@0.90 13.510 mAP@0.95 7.317

**Comment by mugenggeng** [comment]
> Excuse me, could you please provide me with a copy of the CSV_MEAN_100 file
