### ISSUE TITLE
what is the "iou_map = self.localization(subgraph_map)" mean?

### ISSUE THREAD

**Issue by mrlihellohorld** [frostinassiky/gtad#41]
Hi, thank you for your work. when i learn the code of models.py, I don't quite understand this line of code, could you please explain it, https://github.com/frostinassiky/gtad/blob/6deb5b1bc6883b48bd22e0cc593069643c953e3d/gtad_lib/models.py#L235
thank you

**Comment by frostinassiky** [comment]
Hi @mrlihellohorld ,
Good question!

In this line of code, `self.localization` is an instance of the PyTorch module. The input of this module is the aligned feature from SGAlign (see paper for details). This module contains couples of transformations by 1-by-1 2D convolutions. The output of this module shows the confidence of each anchor that belong to an action instance.
