### ISSUE TITLE
Feature for ActivityNet

### ISSUE THREAD

**Issue by DRJ2016** [frostinassiky/gtad#42]
Thank you for sharing the feature of ActivityNet.

The feature of each video in "csv_mean_100.hdf5" is with the dim (100, 400).

May I ask how to get this dimension?

Really thank you!

**Comment by DRJ2016** [comment]
100 represents the 100 snippets and how to get the 400?

**Comment by frostinassiky** [comment]
400 is the feature dimension. Each snippet is represented by a 400d vector.
