### ISSUE TITLE
THUMOS features frame counts

### ISSUE THREAD

**Issue by thematrixduo** [frostinassiky/gtad#48]
Hi, I am looking into your uploaded THUMOS features, and it seems it has one less frame than the original video. For example, in your h5 file ,'video_validation_0000051' has 5090 frames, while the original video has 5091 frames. Could you please let me know what causes the difference? I understand that flow features should have 1 less frame, but how is the rgb frames then aligned? Thanks!

**Comment by frostinassiky** [comment]
Hi @thematrixduo , this is a good catch! 

On THUMOS, we extract frames for the video, then extract the feature with stride=1 frame. There can be one frame missing in the process. 

As suggested from @Phoenix1327  last year, a better alignment can give us a better representation. (Discussion [here](https://github.com/Frostinassiky/gtad/issues/4)) However, 1 frame difference causes less than 0.05-second misalignment, which seems to be acceptable?

**Comment by thematrixduo** [comment]
I see, Thanks!
