### ISSUE TITLE
Questions about classification?

### ISSUE THREAD

**Issue by Scipio1996** [frostinassiky/gtad#6]
In your paper and release the code, the classification score is seemly only a prediction socre scalar rather than a vector. But in inference ,you just use the scalar score to classifiy in the same video. It is more likely action proposal since, the you don't classify the class label in each proposal.

**Comment by frostinassiky** [comment]
Hi @Scipio1996  Thanks for your interest in G-TAD work!
It is very good question. In both the paper and the code, we focus on the localization problem and describe G-TAD as a class-agnostic detector.
The idea of "action proposal" is to develop a second stage that re-score them. In the paper we show that G-TAD detection can be used as proposals and feed into P-GCN model, and make a "two-stage method".
From our experience, it is easier to train a class-agnostic detector than a class-specific one -- but you can try it by yourself! I have happy to receive your feedback :)
